module.exports.descriptors = [
  "New",
  "Blue",
  "Silver",
  "Green",
  "Popular",
  "Striking",
  "Royal",
  "Freedom",
  "Sky",
  "Old",
  "City",
  "National",
  "Muncipal",
  "Village",
  "Regional",
  "State",
  "District",
  "Ancient",
];

module.exports.parkTypes = [
  "Adventure Park",
  "Park and Zoo",
  "Heritage Park",
  "Water Theme Park",
  "Family Park",
  "Tiger Reserve",
  "Forest Reserve",
  "Culture Park",
  "Neighbourhood Park",
  "Botanical Park",
  "Flower Park",
  "National Park",
  "Marine Park",
  "Eco Park",
  "Aqua Park",
  "Bird Park",
  "Fun Park",
  "Snow Park",
  "Game Park",
  "Park and Ruins",
  "Archaeological Park",
];
